services:
  postgres:
    image: postgres:17
    container_name: postgres-db
    environment:
      POSTGRES_DB: school
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student123
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
