# configure the database connection
# Resource folder contains the configurations related to database.
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/school
    username: student
    password: student123

  jpa:
    hibernate:
      ddl-auto: none

    show-sql: true

    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
  error:
    include-message: always
  
  # Support reverse proxy headers from nginx
  servlet:
    context-path: /
  
  tomcat:
    remoteip:
      remote-ip-header: X-Forwarded-For
      protocol-header: X-Forwarded-Proto
      port-header: X-Forwarded-Port
